### ISSUE TITLE
Peer dependency leniency 

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telusdigital/eslint-config#5]
Can we make this peer dependency`"eslint-plugin-react": "7.0.0"` more lenient instead of being so strict to this specific version? It's giving us some warnings when we building our app. Would it be possible to add `~` to the plugin? i.e `"eslint-plugin-react": "~7.0.0"`

**Comment by ahmadnassri** [comment]
make pull request!

**Comment by ryanoglesby08** [comment]
I'd like to add to this to adjust the peer dependencies to match the eslint-airbnb-config peer dependencies. Currently, this package produces peer dependency warnings because they are specifying non-compatible versions:

```
error "@telusdigital/eslint-config#eslint-config-airbnb#eslint-plugin-jsx-a11y@^5.1.1" doesn't satisfy found match of "eslint-plugin-jsx-a11y@6.0.2"
error "@telusdigital/eslint-config#eslint-config-airbnb#eslint-plugin-react@^7.1.0" doesn't satisfy found match of "eslint-plugin-react@7.0.0"
```

```
$ npm info "eslint-config-airbnb@latest" peerDependencies
{ eslint: '^3.19.0 || ^4.3.0',
  'eslint-plugin-jsx-a11y': '^5.1.1',
  'eslint-plugin-import': '^2.7.0',
  'eslint-plugin-react': '^7.1.0' }

$ npm info "@telusdigital/eslint-config" peerDependencies
{ eslint: '^4.3.0',
  'eslint-plugin-import': '^2.7.0',
  'eslint-plugin-jsx-a11y': '^6.0.2',
  'eslint-plugin-react': '7.0.0',
  'eslint-plugin-jest': '^20.0.3' }
```

Specifically, the eslint-plugin-jsx-a11y and the eslint-plugin-react dependencies are not compatible.

I can make a PR for this.

**Comment by ryanoglesby08** [comment]
PR made: #6
